version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    environment:      # environment variable 
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data'
    ports:
      - '5432:5432'   # map local port 3306 to container port 3306
    expose:           # expose container port
      - '5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data:


